### PR TITLE
Add OS switch variable, and make ifWin lazy to allow having multiple in the same string.

### PR DESCRIPTION
**Pull request by bzarco**
Let me know what you think about this... I have a different executable pattern for each OS, and unfortunately VSCode doesn't support scoping config settings by OS. I can't really define multiple advancedExecutables, because all operating systems point to the same files, so it will find executables for the wrong OS...

### CODE REVIEW

**Comment by matepek** [comment]
I like that you are active.

Though I would prefer a different approach. I had some thought about this and I have an idea too: scoping the advanced executables. (I've already regretted adding the {isWin})

its like:
```
"testMate.test.advancedExecutables": [{
  "name": "blabla"
  "mac": { "pattern":"p2" },
  "win": { "pattern":"sdsd" }
   ....
}]
```

I was just waiting for someone with the need. :)

Feel free to contact me anytime. [Gitter](https://gitter.im/CppTestMate/community?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

**Comment by matepek** [comment]
And loved that you wrote tests too ^^

**Comment by matepek** [comment]
Let me quickly develop it. It's not a big change at all.

**Comment by bzarco** [comment]
That is even better :) I didn't love this approach as it made it very unreadable... Thanks!

**Comment by bzarco** [comment]
Btw, you may still want to make {isWin} lazy so that it can be used multiple times...

**Comment by matepek** [comment]
What do you mean?

**Comment by bzarco** [comment]
I meant making the regex capture groups lazy (`(.*?)`) so that `${if(isWin)}` can be used multiple times in a string (e.g. `"${if(isWin)}<W>${else}<U>${endif} blah blah ${if(isWin)}<W>${else}<U>${endif}"`). See the changes here. (I won't need it anymore with your solution, but easy improvement)

**Pull request closed without merging**
