### PR TITLE
Native UI: Fix missing test explorer icon

### PR DESCRIPTION
**Pull request by SizaSL**
This PR will fix the missing test explorer icon when native ui was enabled in Test Explorer settings

### CODE REVIEW

**Comment by matepek** [comment]
How can it be reproduced?

**Comment by SizaSL** [comment]
> How can it be reproduced?

Just download from latest master 8d00a and it didn't work. Set native ui in Test Explorer settings and restart. Test Explorer settings won't show up after restart.

**Comment by matepek** [comment]
I'm thinking that [this](https://github.com/microsoft/vscode-test-adapter-converter/blob/main/package.json#L19) might be good enough.
TBH I would rather not to add `*`. I consider my extension resource intensive.

**Comment by SizaSL** [comment]
> I'm thinking that [this](https://github.com/microsoft/vscode-test-adapter-converter/blob/main/package.json#L19) might be good enough.
> TBH I would rather not to add `*`. I consider my extension resource intensive.

Agree. Have you tested it? I did a quick test and didn't work. The advantage of using "*" is you don't have to wait for loading tests because it has been loaded long before. Why don't we use this for a temporary fix at the moment until we found the right activation event?

**Pull request closed without merging**
