### PR TITLE
Add option to use Google's internal GTest flags.

### PR DESCRIPTION
**Pull request by bzarco**
Inside Google, GTest binaries have `--gunit_*` flags instead of
`--gtest_*`. This change allows using the extension for tests compiled
in Google's internal codebase.

### CODE REVIEW

**Comment by bzarco** [comment]
Hi Mate, first of all, awesome work with the extension, it is very useful!

This change is a bit tricky, as it obviously doesn't affect any of your current users... Please let me know if you want to handle it in a different way.

Thanks!

**Comment by matepek** [comment]
Hello,
Thanks^^ It was a long journey.

I think we might can come up with a slightly better solution.

But first, I need some "insider" info:
What is the output of the executable if it is called with `--help`?

In case of the public version it is: 
```
This program contains tests written using Google Test. You can use the
following command line flags to control its behavior:

Test Selection:
  --gtest_list_tests
      List the names of all tests instead of running them. The name of
      TEST(Foo, Bar) is "Foo.Bar".
...
```

If we could distinguish between the two versions then the extension could automatically determine the **prefix**.

Please attach the full output of the executable started with `--help`.

**Comment by matepek** [comment]
Also.. Do you have different prefix in case of gmock too?

**Comment by matepek** [comment]
Actually.. Based on [this](https://github.com/google/googletest/blob/master/googletest/src/gtest.cc#L6256)
It can be detected automatically.

**Comment by matepek** [comment]
I'm already on this. So I close the PR, I hope you don't mind. Your contribution is appreciated. Looking forward to the next one ;)

**Comment by bzarco** [comment]
Sounds good! as long as we get the functionality :)

Let me know if I can help test it once you have it done.

Thanks!

**Comment by bzarco** [comment]
Since you asked, this is the output from `--help`:

```
This program contains tests written using Google Test. You can use the
following command line flags to control its behavior:

Test Selection:
  --gunit_list_tests
      List the names of all tests instead of running them. The name of
      TEST(Foo, Bar) is "Foo.Bar".
```

Unfortunately relying on the `--help` output will not work for our linux builds for example, as the help output is different. I can change the regex so that it recognizes it as gtest (it prints a message saying to use -helpfull, I believe they are built with a different infrastructure), but you will not be able to find the prefix...

**Comment by matepek** [comment]
I see, that sucks..
I mean that recognition will give value everybody who wants to use gtest and the extension with different prefix.
But this is really specific..
So if I understand it right on linux it just prints a help message like `use -helpfull`. 
Can I see the output? And what is the result of running the exec with that argument?

**Comment by bzarco** [comment]
I definitely think the recognition is a nice default, similarly to how you do it without the regex, as it will handle the majority of the cases. I know it is very specific, sorry about that! And thanks for taking the time to look into it. If I call it with `-helpful` it prints all the flags compiled into the binary. The gtest flags are printed as well, just not in the same format/order...

For example, `test -helpful | grep gunit_list_tests` prints:

```
    --gunit_list_tests (List all tests without running them.); type: bool;
```

**Comment by matepek** [comment]
And what is the output for `--help`?

Let's say that it prints that special output while using `--help` then it can rerun the executable with with that special argument. 

It is a custom solution but if this makes your jobs easier I don't mind because it is a small change.
This is just for you guys. Google give so much to the community I think I am biased a bit. ^^

**Comment by bzarco** [comment]
Thanks! :)

```
$ path/to/test_name --help 
test_name: path/to/test_name

  No modules matched: use -helpfull

Try --helpfull to get a list of all flags.
```

Imo, calling --helpfull is not necessary, and it prints *a lot*. You can just assume `--gunit_*` flags if the output of `--help` is like that (since public gtest will never look like that, nor the other test frameworks you support now or in the future).

**Comment by matepek** [comment]
Even better.

**Pull request closed without merging**
